---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  storage:
    size: 20Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "400"
      max_locks_per_transaction: "128"
      shared_buffers: 256MB
      timescaledb.telemetry_level: "off"
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 6Gi
  monitoring:
    enablePodMonitor: true

  # 1. Point to the old cluster name via anchor
  bootstrap:
    recovery:
      source: &previousCluster postgres18-v1

  backup:
    retentionPolicy: 30d
    # 2. Anchor the entire base configuration map
    barmanObjectStore: &barmanConfig
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://cloudnative-pg/
      endpointURL: https://2f426071712d0a81525d59ac8b12f4bb.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: aws-access-key-id
        secretAccessKey:
          name: cloudnative-pg-secret
          key: aws-secret-access-key
      # 3. Explicitly set the name for your NEW backup trail
      serverName: postgres18-v2

  externalClusters:
    - name: *previousCluster
      barmanObjectStore:
        # 4. Merge all shared settings (including endpointURL) from the anchor
        <<: *barmanConfig
        # 5. Override ONLY the server name to point to your old data
        serverName: *previousCluster

