---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wizarr-stripe-bridge
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: wizarr-stripe-bridge-secret
    template:
      data:
        STRIPE_API_KEY: "{{ .STRIPE_API_KEY }}"
        STRIPE_WEBHOOK_SECRET: "{{ .STRIPE_WEBHOOK_SECRET }}"
        STRIPE_PAYMENT_LINK: "{{ .STRIPE_PAYMENT_LINK }}"
        WIZARR_API_KEY: "{{ .WIZARR_API_KEY }}"
        RESEND_API_KEY: "{{ .RESEND_API_KEY }}"
        JELLYFIN_WEBHOOK_SECRET: "{{ .JELLYFIN_WEBHOOK_SECRET }}"
  dataFrom:
    - extract:
        key: wizarr-stripe-bridge
