---
ingress:
  - hostname: "*.ahla.dev"
    service: https://envoy-external.networking.svc.cluster.local
    originRequest:
      http2Origin: true
      originServerName: "external.ahla.dev"
  - service: http_status:404
