---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/namespace
resources:
  - ./autobrr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./bazarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./seasonpackerr/ks.yaml
  - ./jellyfin/ks.yaml
  - ./seerr/ks.yaml
  - ./wizarr/ks.yaml
