---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ahla-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ahla-runner-secret
    template:
      data:
        github_app_id:              "{{ .BOT_APP_ID }}"
        github_app_installation_id: "{{ .BOT_APP_INSTALLATION_ID }}"
        github_app_private_key:     "{{ .BOT_APP_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: ahlabot
