---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: external-dns-cloudflare-secret
    template:
      data:
        CF_DOMAIN_MAIN_ZONE_ID: "{{ .CLOUDFLARE_DOMAIN_MAIN_ZONE_ID }}"
        CF_DOMAIN_BACKUP_ZONE_ID: "{{ .CLOUDFLARE_DOMAIN_BACKUP_ZONE_ID }}"
        CF_API_TOKEN: "{{ .CLOUDFLARE_API_TOKEN }}"
  dataFrom:
    - extract:
        key: cloudflare
