---
version: "3"

tasks:

  krew:
    desc: Set up Krew tools
    cmds:
      - kubectl krew install cert-manager cnpg browse-pvc node-shell view-secret
    preconditions:
      - kubectl krew version
      - which kubectl
  upgrade-tolosctl:
    desc: Upgrade talosctl
    cmds:
      - sudo rm /usr/local/bin/talosctl && curl -sL https://talos.dev/install | sh
    preconditions:
      - test -f /usr/local/bin/talosctl
