---
version: "3"

tasks:

  krew:
    desc: Set up Krew tools
    cmds:
      - kubectl krew install cert-manager cnpg browse-pvc node-shell rook-ceph view-secret
    preconditions:
      - kubectl krew version
      - which kubectl
