---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
addresses:
  - address: 192.168.10.10/24
routes:
  - gateway: 192.168.10.1

---
machine:
  install:
    diskSelector:
      model: CT2000P310SSD8
      serial: 2538533351EB

---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: vore.hythm.net

--- 
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 512GiB
    
---   
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-hostpath
provisioning:
  diskSelector:
    match: system_disk
  minSize: 1TB


