---
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: daily
spec:
  enabled: true
  moverVolumes:
    - mountPath: repository
      volumeSource:
        nfs:
          path: /data/backup/kopia
          server: chthon.hythm.net
  repository:
    repository: volsync-maintenance-secret
  trigger:
    schedule: 30 3,15 * * *
