---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ahla-domains
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: ahla-domains
  dataFrom:
    - extract:
        key: ahla_domains
