---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hythm-net
spec:
  dnsNames:
    - hythm.net
    - "*.hythm.net"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: hythm-net-tls
  usages:
    - digital signature
