---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ahla-domain
spec:
  dnsNames:
    - "${DOMAIN}"
    - "*.${DOMAIN}"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: ahla-domain-tls
  usages:
    - digital signature
