---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: ${APP}
  trigger:
    schedule: 4 2 * * *
  kopia:
    storageClassName: ${VOLSYNC_STORAGECLASS:=openebs-hostpath}
    copyMethod: Direct
    compression: zstd-fastest
    accessModes:
      - ${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce}
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            path: /data/backup/qube/kopia
            server: chthon.hythm.net
    parallelism: 2
    repository: ${APP}-volsync-secret
    retain:
      hourly: 24
      daily: 7
