---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: &name bitwarden-secrets-manager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      auth:
        secretRef:
          credentials:
            key: token
            name: *name
            namespace: external-secrets
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt
      projectID:      8cfc9211-d42e-45af-a73f-1e52d95c417b
      organizationID: 9cd50188-f9ac-4069-8b20-b43500728568

